[package]
name = "rust_browser"
version = "0.1.0"
authors = ["Nick Vanden Eynde <nick@vitanick.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
